"""Migration Update

Revision ID: 0d9e60fdaa27
Revises: 919e98009ef6
Create Date: 2024-10-16 13:18:16.045412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d9e60fdaa27'
down_revision: Union[str, None] = '919e98009ef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voceovers', sa.Column('voiceover', sa.String(length=70), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voceovers', 'voiceover')
    # ### end Alembic commands ###
